### ISSUE TITLE
Not on Maven Central

### ISSUE THREAD

**Issue by psulightning** [yantonov/gitdep-maven-plugin#1]
Can this be added to Maven central please?  Or is this project dead?

**Comment by yantonov** [comment]
I want to fix some issue and publish it.

**Comment by yantonov** [comment]
Moreover some functionality must be added (for example checkout branch or commit/tag), before publishing.

**Comment by psulightning** [comment]
That would be great. I have your plugin as a local dependency right now.  It works, except for the above you stated.

**Comment by yantonov** [comment]
Already on. 
Version number is changed according to semver, be careful. Initial version number is 0.1.0. 
Thanks!

**Comment by psulightning** [comment]
Thanks.
