### ISSUE TITLE
Dependency not found...

### ISSUE THREAD

**Issue by Stephan972** [yantonov/gitdep-maven-plugin#2]
I have tried to use the plugin and I got the following error message:

> [ERROR] Failed to execute goal com.yantonov:gitdep-maven-plugin:0.1.0:clone (clone) on project express-tube-site-builder: Dependency net.codemirror:codemirror is not found in pom.xml -> [Help 1]

Here is the configuration in my pom:

```
<plugin>
    <groupId>com.yantonov</groupId>
    <artifactId>gitdep-maven-plugin</artifactId>
    <version>0.1.0</version>
    <configuration>
        <gitDependencies>
            <gitDependency>
                <groupId>net.codemirror</groupId>
                <artifactId>codemirror</artifactId>
                <repositoryLocation>https://github.com/codemirror/CodeMirror</repositoryLocation>
                <branch>master</branch>
            </gitDependency>
        </gitDependencies>
    </configuration>
    <executions>
        <execution>
            <id>get-git-dependencies</id>
            <goals>
                <goal>exec</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

What am I missing?

**Comment by yantonov** [comment]
It seems pom.xml does not reference codeMirror artifact inside dependency section. This is format check (its not necessary to clone artifacts which are not referenced by pom file).

**Comment by Stephan972** [comment]
When I add codeMirror to the pom.xml, Maven complains it doesn't find the dependency. What am I missing?

**Comment by yantonov** [comment]
Please, cite the whole pom file, not just plugin section.

**Comment by yantonov** [comment]
I suppose <dependencies/dependency> section does not reference codeMirror repository, thats why i suggest to post the whole pom.file (to ensure and locate/fix problem).

**Comment by yantonov** [comment]
Try to check dependecies/dependency section to ensure you include codeMirror dependency in it.

**Comment by Stephan972** [comment]
The groupId was incorrect.
